### ISSUE TITLE
[Forbedring] Anse arrangementer som "kommende" opptil 12 timer etter sluttid

### ISSUE THREAD

**Issue by Torsteinws** [Motstanden/motstanden-website#65]
For arrangementer som ikke har sluttid burde sluttid anses som midnatt den dagen arrangementet starter

**Comment by 1-Bart-1** [comment]
hvorfor står det bare gamle arrangementer på development nettsiden og nye på publiserte nettsiden

**Comment by Torsteinws** [comment]
Fikset i #80
