### ISSUE TITLE
[Forslag] Nettside for hvert styre

### ISSUE THREAD

**Issue by 1-Bart-1** [Motstanden/motstanden-website#71]

**Comment by Torsteinws** [comment]
Forslaget er basert på dette statuttforslaget: motstanden/motstanden-statutter#19

**Comment by Torsteinws** [comment]
Det er nå opprettet en repo for dette: [Motstanden/motstanden-styresider](https://github.com/Motstanden/motstanden-styresider)

Repo-en er live på [https://styret.motstanden.no/](https://styret.motstanden.no/)

Neste steg er å integrere den inn i [motstanden.no](motstanden.no)

**Comment by Torsteinws** [comment]
Linker er nå integrert i nettsiden: https://motstanden.no/styrets-nettsider

Det er dog rom for forbedringer!

**Comment by Torsteinws** [comment]
# Gjenstående arbeid
Vi ønsker å kunne oppdatere linkene til styrenettsidene uten å oppdatere kildekoden til prosjektet.
Det er per nå ikke mulig ettersom linkene er hardkodet i front-end.

Vi ønsker derfor:
- Opprette en tabell for styrenettsidene i databasen.
- Klient må kunne hente styrenettsidene fra databasen og kunne forstå dataen.
- Klient må kunne slette, redigere og legge til ny data i databasen.

**Comment by Torsteinws** [comment]
Implementert
