### ISSUE TITLE
Ikke lov å låne bort hodeplagg

### ISSUE THREAD

**Issue by Ninatgun** [Motstanden/motstanden-website#72]
Andre stjeler og låner hodeplagg for gøy på fylla og ellers hele tiden. Dette resulterer i stress og tapt Hodeplagg. Foreslår derfor at hodeplagget er privat uten mulighet for utlån. Så slipper man å føle seg frekk når man ikke vil låne bort, man kan si det man faktisk ikke har lov.

**Comment by Torsteinws** [comment]
Ikke relevant for nettsiden. Regner med at dette skulle vært skrevet på [statutt siden vår](https://github.com/Motstanden/motstandens-statutter)
